remote_theme: sighingnow/jekyll-gitbook

title: My Molecular Dynamics Notes
description: Notes on molecular dynamics practice

syntax_highlighter_style: pastie

toc:
    enabled: true
    h_min: 2
    h_max: 3
